export const AUTH_SAGAS: string = 'AUTH'
export const FETCH_CLIENTS_SAGAS: string = 'FETCH_CLIENTS_SAGA'
export const FETCH_REASONS_SAGAS: string = 'FETCH_REASONS_SAGA'
export const FETCH_APPOINTMENTS_SAGAS: string = 'FETCH_APPOINTMENTS_SAGA'
export const FETCH_APPOINTMENT_STRUCTURE_SAGA: string =
  'FETCH_APPOINTMENT_STRUCTURE_SAGA'
export const UPDATE_NETWORK_STATUS_SAGAS: string = 'UPDATE_NETWORK_STATUS_SAGA'
export const SYNC_APPOINTMENTS_SAGAS: string = 'SYNC_APPOINTMENTS_SAGA'
export const SYNC_APPOINTMENT_SAGA: string = 'SYNC_APPOINTMENT_SAGA'
export const SET_STEP_INFO_LABELS_FROM_STRUCTURE_SAGA: string =
  'SET_STEP_INFO_LABELS_FROM_STRUCTURE_SAGA'
export const CHANGE_LANGUAGE_SAGAS: string = 'CHANGE_LANGUAGE_SAGA'
export const CHECK_IN_APPOINTMENT_SAGAS: string = 'CHECK_IN_APPOINTMENT_SAGA'
export const LOGOUT_SAGA: string = 'LOGOUT_SAGA'
export const CREATE_APPOINTMENT_SAGA: string = 'CREATE_APPOINTMENT_SAGA'
export const UPDATE_APPOINTMENT_SAGA: string = 'UPDATE_APPOINTMENT_SAGA'
export const DELETE_APPOINTMENT_SAGA: string = 'DELETE_APPOINTMENT_SAGA'

export const SET_ON_DATASET_REDUCER: string = 'SET_ON_DATASET_REDUCER'
export const PUSH_TO_DATASET_LIST_REDUCER: string =
  'PUSH_TO_DATASET_LIST_REDUCER'
export const UPDATE_TO_DATASET_LIST_REDUCER: string =
  'UPDATE_TO_DATASET_LIST_REDUCER'
export const DELETE_DATASET_LIST_REDUCER: string = 'DELETE_DATASET_LIST_REDUCER'

export const FETCH_CLIENTS_REDUCER: string = 'FETCH_CLIENTS_REDUCER'
export const FETCH_REASONS_REDUCER: string = 'FETCH_REASONS_REDUCER'
export const CLEAR_REASONS_REDUCER: string = 'CLEAR_REASONS_REDUCER'
export const CLEAR_CLIENTS_REDUCER: string = 'CLEAR_CLIENTS_REDUCER'
export const CHECK_NETWORK_SAGA: string = 'CHECK_NETWORK_SAGA'
export const RUN_TASKS_SAGA: string = 'RUN_TASKS_SAGA'
export const SYNC_APPOINTMENTS_NOTIFICATIONS_SAGA: string =
  'SYNC_APPOINTMENTS_NOTIFICATIONS_SAGA'
export const SET_NOTIFICTION_REDUCER: string = 'SET_NOTIFICTION_REDUCER'
export const SET_NOTIFICTION_SAGA: string = 'SET_NOTIFICTION_SAGA'
export const NOTIFICATION_WAS_TAPPED_SAGA: string =
  'NOTIFICATION_WAS_TAPPED_SAGA'
export const CLEAR_NOTIFICTIONS_REDUCER: string = 'CLEAR_NOTIFICTIONS_REDUCER'
export const LOGIN_SAGA: string = 'LOGIN_SAGA'
export const CALLBACK_VOID_SAGA: string = 'CALLBACK_VOID_SAGA'
export const CLEAR_REDUCER_SAGA: string = 'CLEAR_REDUCER_SAGA'
export const REGISTER_SAGA: string = 'REGISTER_SAGA'
export const HOME_SAGA: string = 'HOME_SAGA'

export const REQUEST_BUDGET_SAGA: string = 'REQUEST_BUDGET_SAGA'
